-- Copyright (C) 2013-2014 Paweł Jojczyk
--
-- This program is free software: you can redistribute it and/or modify
-- it under the terms of the GNU General Public License as published by
-- the Free Software Foundation, either version 3 of the License, or
-- (at your option) any later version.
--
-- This program is distributed in the hope that it will be useful,
-- but WITHOUT ANY WARRANTY; without even the implied warranty of
-- MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
-- GNU General Public License for more details.
--
-- You should have received a copy of the GNU General Public License
-- along with this program.  If not, see <http://www.gnu.org/licenses/gpl-3.0.html>.

CREATE TABLE USERS (
	ID INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,
	NAME VARCHAR(30) NOT NULL,
	PASSWORD VARCHAR(30) NOT NULL,
	NOT_EXPIRED BOOLEAN NOT NULL,
	NOT_LOCKED BOOLEAN NOT NULL,
	CREDENTIALS_NOT_EXPIRED BOOLEAN NOT NULL,
	ENABLED BOOLEAN  NOT NULL,
	CONSTRAINT USERS_NAME_UNIQUE UNIQUE (NAME)
);

CREATE TABLE AUTHORITIES (
	ID INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,
	ROLE VARCHAR(20) NOT NULL,
	CONSTRAINT AUTHORITIES_ID_ROLE_UNIQUE UNIQUE (ID, ROLE)
);

CREATE TABLE USERS_AUTHORITIES (
	USER_ID INTEGER NOT NULL FOREIGN KEY REFERENCES USERS(ID),
	AUTHORITY_ID INTEGER NOT NULL FOREIGN KEY REFERENCES AUTHORITIES(ID),
	CONSTRAINT USERS_AUTHORITIES_PK PRIMARY KEY (USER_ID, AUTHORITY_ID)
);
